import Head from 'next/head'
import {GetStaticProps} from 'next'
import StoreHeader from '@/components/StoreHeader'
import {baseApiUrl} from '@/lib/telegram'
import Image from 'next/image'
import s from '../styles/Store.module.scss'
import {HiMinus, HiPlus} from 'react-icons/hi'

export default function Store({products}: { products: any }) {
  console.log(products)

  return (
    <>
      <Head>
        <title>No Smoke Division</title>
        <meta name="description" content="Магазин снюса No Smoke Division"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <main>
        <StoreHeader/>
        <div className={s.productList}>
          {products.map((product: any) => (
            <div className={s.productCard} key={product.id}>
              <Image src={product.images[0].src} alt={'Фото ' + product.name} className={s.productImage} width={140}
                     height={140}/>
              <div className={s.productName}>
                <span>{product.name} </span>
                <span className={s.price}>{product.price} ₽</span>
              </div>
              <div className={s.buttons}>
                <button className={s.buttonRemove}><HiMinus/></button>
                <button className={s.buttonAdd}><HiPlus/></button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  // https://nextjs.org/docs/basic-features/data-fetching/get-static-props
  const products = await fetch(baseApiUrl + '/products?per_page=33').then((res) => res.json())

  return {
    props: {
      products,
    },
  }
}


// import Head from 'next/head'
// import Image from 'next/image'
// import {Roboto} from 'next/font/google'
// import styles from '@/styles/Store.module.scss'
//
// // const inter = Roboto({ subsets: ['cyrillic'], weight: '400' })
//
// // main component for the store
// // component has sticky header with arrow to open dropdown with search filters, search input, search button, cart button
// // component has main section with products
// // component does not have footer
//
// export default function Home() {
// return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         <div className={styles.header}>
//           <div className={styles.header__logo}>
//             <Image
//               src="/logo.png"
//               alt="Logo"
//               width={100}
//               height={100}
//               priority
//             />
//           </div>
//           <div className={styles.header__search}>
//             <div className={styles.header__search__filters}>
//               <div className={styles.header__search__filters__dropdown}>
//                 <div className={styles.header__search__filters__dropdown__arrow}></div>
//                 <div className={styles.header__search__filters__dropdown__content}></div>
//               </div>
//               <div className={styles.header__search__filters__dropdown}>
//                 <div className={styles.header__search__filters__dropdown__arrow}></div>
//                 <div className={styles.header__search__filters__dropdown__content}></div>
//               </div>
//               <div className={styles.header__search__filters__dropdown}>
//                 <div className={styles.header__search__filters__dropdown__arrow}></div>
//                 <div className={styles.header__search__filters__dropdown__content}></div>
//               </div>
//             </div>
//             <div className={styles.header__search__input}>
//               <input type="text" placeholder="Search..." />
//             </div>
//             <div className={styles.header__search__button}>
//               <button>Search</button>
//             </div>
//           </div>
//           <div className={styles.header__cart}>
//             <div className={styles.header__cart__icon}>
//               <Image
//                 src="/cart.png"
//                 alt="Cart"
//                 width={100}
//                 height={100}
//                 priority
//               />
//             </div>
//             <div className={styles.header__cart__count}>
//               <p>0</p>
//             </div>
//           </div>
//         </div>
//         <div className={styles.main}>
//           <div className={styles.main__products}>
//             <div className={styles.main__products__product}>
//               <div className={styles.main__products__product__image}>
//
// }
//

// import Head from 'next/head'
//
// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app"/>
//         <meta name="viewport" content="width=device-width, initial-scale=1"/>
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//
//       </main>
//       {/*<main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>src/pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>
//
//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>
//
//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>
//
//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>
//
//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>*/}
//     </>
//   )
// }
